# Generated by Django 3.0.4 on 2020-05-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mail',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, '女'), (1, '男')], null=True, verbose_name='性别'),
        ),
    ]
