# Generated by Django 3.0.4 on 2020-05-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingauth', '0002_menulist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulist',
            name='children',
        ),
        migrations.AddField(
            model_name='menulist',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentlevel', to='meetingauth.MenuList', verbose_name='子菜单'),
        ),
    ]
