# Generated by Django 3.0.4 on 2020-05-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingauth', '0004_auto_20200503_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulist',
            name='style',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='样式'),
        ),
    ]
