# Generated by Django 3.0.4 on 2020-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingauth', '0005_menulist_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='style',
            field=models.CharField(default='el-icon-menu', max_length=20, verbose_name='样式'),
        ),
    ]
