# Generated by Django 3.0.4 on 2020-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingauth', '0006_auto_20200503_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulist',
            name='path',
            field=models.CharField(default='', max_length=10, verbose_name='路由'),
            preserve_default=False,
        ),
    ]
