# Generated by Django 3.0.4 on 2020-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingauth', '0007_menulist_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='path',
            field=models.CharField(default='', max_length=20, verbose_name='路由'),
        ),
    ]
