# Generated by Django 3.0.4 on 2020-05-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingauth', '0009_auto_20200504_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('path', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='路由')),
                ('style', models.CharField(default='el-icon-menu', max_length=20, verbose_name='样式')),
                ('level', models.PositiveSmallIntegerField(verbose_name='级别')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentlevel', to='meetingauth.Permission', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.DeleteModel(
            name='MenuList',
        ),
    ]
