# Generated by Django 3.0.4 on 2020-05-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingauth', '0010_auto_20200504_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20, verbose_name='角色名称')),
                ('role_desc', models.CharField(max_length=20, verbose_name='角色描述')),
                ('permissions', models.ManyToManyField(related_name='perm', to='meetingauth.Permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
    ]
