# Generated by Django 2.1.7 on 2020-05-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
            ],
            options={
                'verbose_name_plural': '会议室设备',
                'verbose_name': '会议室设备',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('site', models.CharField(max_length=100, verbose_name='会议室位置')),
                ('nums', models.PositiveIntegerField(verbose_name='人数')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '正常'), (1, '报修'), (2, '占用'), (3, '停用')], default=0, verbose_name='状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('reserve_status', models.PositiveSmallIntegerField(choices=[(0, '可预订'), (1, '已预订')], default=0, verbose_name='预定状态')),
                ('image', models.ImageField(upload_to='meetingroom', verbose_name='会议室图片')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='添加用户')),
                ('equipment', models.ManyToManyField(to='meetingroom.MeetingRoomEquipment', verbose_name='设备')),
            ],
            options={
                'verbose_name_plural': '会议室信息',
                'verbose_name': '会议室信息',
            },
        ),
    ]
