# Generated by Django 2.1.7 on 2020-05-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroominfos',
            name='image',
            field=models.ImageField(default='liqin.jpg', upload_to='meetingroom', verbose_name='会议室图片'),
        ),
    ]
