# Generated by Django 3.0.4 on 2020-05-02 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetingroom', '0002_auto_20200501_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetRoomReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('begin_datetime', models.DateTimeField(verbose_name='开始时间')),
                ('over_datetime', models.DateTimeField(verbose_name='结束时间')),
                ('remarks', models.CharField(max_length=100, verbose_name='备注')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '通过'), (1, '未通过'), (2, '发起'), (3, '撤销'), (4, '会议未举行')], default=2, verbose_name='状态')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chair', to=settings.AUTH_USER_MODEL, verbose_name='主持人')),
                ('name', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room', to='meetingroom.MeetingRoomInfos', verbose_name='会议室')),
                ('participants', models.ManyToManyField(related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='参与人')),
            ],
            options={
                'verbose_name': '会议室预定',
                'verbose_name_plural': '会议室预定',
            },
        ),
    ]
