# Generated by Django 3.0.4 on 2020-05-02 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetingroom', '0003_meetroomreserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetroomreserve',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
    ]
