# Generated by Django 3.0.4 on 2020-05-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0005_auto_20200502_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroominfos',
            name='reserve_status',
        ),
    ]
