# Generated by Django 2.2.10 on 2020-05-15 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0006_remove_meetingroominfos_reserve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroomequipment',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingroominfos',
            name='image',
            field=models.ImageField(default='liqin.jpg', upload_to='meetingroom/', verbose_name='会议室图片'),
        ),
    ]
