# Generated by Django 2.2.10 on 2020-05-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0007_auto_20200515_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroomequipment',
            name='infos',
            field=models.CharField(default=1, max_length=100, verbose_name='设备描述'),
            preserve_default=False,
        ),
    ]
