# Generated by Django 2.2.10 on 2020-05-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0008_meetingroomequipment_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroomequipment',
            name='infos',
            field=models.CharField(default='', max_length=100, verbose_name='设备描述'),
        ),
    ]
